-- FreeFlow Marketing — Week 4 schema
--
-- HOW TO RUN
--   Supabase dashboard → SQL Editor → New query → paste → Run
--   Safe to re-run: drops and recreates the table.
--
-- Additive. Does not touch projects (Week 0), core_outputs (Week 1),
-- research_records (Week 2), pricing_scenarios / user_prefs (Week 3).
--
-- Per-user from the start, matching the auth-era policy shape the accounts
-- migration applied to the older tables (user_id = auth.uid()). No public
-- insert: marketing assets belong to the account that generated them.

drop table if exists public.marketing_assets;

create table public.marketing_assets (
  id          uuid primary key default gen_random_uuid(),

  user_id     uuid not null references auth.users(id) on delete cascade,

  -- What kind of asset this row holds. jsonb content, below, varies by kind,
  -- which is why the shape is not a fixed column set.
  kind        text not null
              check (kind in ('post', 'script', 'calendar', 'headline')),

  -- The asset itself. jsonb because a post, a script, a calendar and a chosen
  -- headline do not share a shape, and a column per type would be mostly nulls.
  content     jsonb not null,

  -- Provenance, the same discipline core_outputs uses: was this generated by
  -- the model or produced by the heuristic seed fallback. A saved asset with
  -- no provenance is a claim with no source.
  extractor   text not null check (extractor in ('model', 'heuristic')),

  created_at  timestamptz not null default now()
);

create index marketing_assets_user_idx
  on public.marketing_assets (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Row Level Security — own rows only, all four verbs scoped to auth.uid()
-- ---------------------------------------------------------------------------

alter table public.marketing_assets enable row level security;

drop policy if exists "Own rows: select" on public.marketing_assets;
create policy "Own rows: select" on public.marketing_assets
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "Own rows: insert" on public.marketing_assets;
create policy "Own rows: insert" on public.marketing_assets
  for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "Own rows: update" on public.marketing_assets;
create policy "Own rows: update" on public.marketing_assets
  for update to authenticated using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "Own rows: delete" on public.marketing_assets;
create policy "Own rows: delete" on public.marketing_assets
  for delete to authenticated using (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Verify
-- ---------------------------------------------------------------------------
-- Expect 0 rows and exactly 4 policies (select, insert, update, delete).

select
  (select count(*) from public.marketing_assets) as row_count,
  (select count(*) from pg_policies
     where schemaname = 'public' and tablename = 'marketing_assets') as policy_count,
  (select string_agg(cmd, ', ' order by cmd) from pg_policies
     where schemaname = 'public' and tablename = 'marketing_assets') as commands;
